name: cosmo-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyterlab
  - astropy
  - pip
  - pip:
      - classylss   # opcional
